// ===============================
// PBODY FULLSTACK ACADEMY
// AI TYPES
// ===============================

export const AI_TYPES = {

  INITIALIZE_AI: "INITIALIZE_AI",

  OPEN_CHAT: "OPEN_CHAT",

  CLOSE_CHAT: "CLOSE_CHAT",

  TOGGLE_CHAT: "TOGGLE_CHAT",

  SET_LOADING: "SET_LOADING",

  SET_TYPING: "SET_TYPING",

  SEND_MESSAGE: "SEND_MESSAGE",

  RECEIVE_MESSAGE: "RECEIVE_MESSAGE",

  CLEAR_CHAT: "CLEAR_CHAT",

  DELETE_MESSAGE: "DELETE_MESSAGE",

  SET_PAGE: "SET_PAGE",

  SET_COURSE: "SET_COURSE",

  SET_LESSON: "SET_LESSON",

  SET_USER: "SET_USER",

  SET_SUGGESTIONS: "SET_SUGGESTIONS",

  UPDATE_PROGRESS: "UPDATE_PROGRESS",

  RESET_AI: "RESET_AI"

};